version: '3'

services:
  files-api:
    build: .
    ports:
      - "8080:8080"
    environment:
      BASIC_AUTH_USERNAME: ${BASIC_AUTH_USERNAME}
      BASIC_AUTH_PASSWORD: ${BASIC_AUTH_PASSWORD}
      LOCAL_DB_PATH: ${LOCAL_DB_PATH}
      LOCAL_DB_NAME: ${LOCAL_DB_NAME}
      LOCAL_FILES_PATH: ${LOCAL_FILES_PATH}
    volumes:
      - ./local:/local

